export const appImages = {
    loginbg: require('../assets/images/loginbg.svg'),
    hotelImg: require('../assets/images/hotelImg.svg'),
    boximg: require('../assets/images/boximg.svg'),
    tableAvailable: require('../assets/images/AvailableImg.svg'),
    tableOccupied: require('../assets/images/occupiedImg.svg'),
    prepareimage: require('../assets/images/Prepareimg.svg'),
    tableimg: require('../assets/images/Tableimg.svg'),
    clockimg: require('../assets/images/clock.svg'),
    homeImg: require('../assets/images/homeImg.svg'),
    dineimg: require('../assets/images/dineImg.svg'),
    billimg: require('../assets/images/billImg.svg'),
    settingImg: require('../assets/images/settingImg.svg'),
    floorImg: require('../assets/images/floorImg.svg'),
    menuImg: require('../assets/images/menusImg.svg'),
    userImg: require('../assets/images/userImg.svg'),
    usertableImg: require('../assets/images/usertableimg.svg'),
    profileImg: require('../assets/images/profilePic.svg'),
    managerImg: require('../assets/images/managerImg.svg'),
    waiterImg: require('../assets/images/waiterImg.svg'),
    personPic:require('../assets/images/personPic.svg')
}
